credentials:
  aws: /.aws/credentials
  gcp:
  mysql:
    # remote_host:
    remote_host: 127.0.0.1
    user: discoverylocal
    password: 1qaz8ik,
    name: getlistserver_sdk

filter:
  match:
    status: ["in_used"]
  not_match:
    product: ["MPS_DEV", "MTO_ShareSys", "GT_Devops", "FBS_Dev", "SO6_Access", "SO6_Payment"]
    selv1: ["truongln", "vihct", "phongnvd"]
    ip: ["118.102.3.11"]
